### ISSUE TITLE
Warn About Missing Keys In Suppress Mode

### ISSUE THREAD

**Issue by moebrowne** [Synapse791/quark#1]
It would be nice if when you tell Quark to suppress missing key errors (with the  `-s` argument) that it still warns you, maybe in orange, and carries on anyway.

This way if you change something and a bunch of orange turns up you know something is wrong rather that it just saying `successfully processed...`

**Comment by itmecho** [comment]
I'd say this was a bug as it's misinformation

**Comment by itmecho** [comment]
This is fixed by https://github.com/Synapse791/quark/commit/5a5c5649fbcc3af1cb45b4c440476465841b827e
